### ISSUE TITLE
Mixin Conflict with Gregtech Modern

### ISSUE THREAD

**Issue by sleepy-evelyn** [LordDeatHunter/Alloy-Forgery#125]
Game crashes with Gregtech Modern installed :P. Seems to be a Mixin Conflict.

**Gregtech Modern version:** 1.20.1-1.0.18-fabric
**Crash Report:** https://gist.github.com/sleepy-evelyn/51ae8df42069d11b6255f910dc7cbcdf

**Comment by BasiqueEvangelist** [comment]
You sure this is alloy forgery or owo-lib? Can't seem to find any relevant mixins
Oh, and also  
‍ 
‍ 
‍ 
‍ 
‍ 
‍ 
‍ 
greg

**Comment by Dragon-Seeker** [comment]
For the most part, this is an issue with Greg Tech's injection point leading to an issue where a variable LVM table is altered leading to their mixin crashing. AF and owo are seen due to classloading of the inflicted class that Greg is mixing into and has nothing to do with AF or owo from the crash log. 

Have you tested without AF and owo to confirm that such is not another mod's fault or Greg tech?

**Comment by sleepy-evelyn** [comment]
It's fine they dropped support for Fabric anyway so none of this really matters anymore going forward for newer versions.
