### ISSUE TITLE
Incompatible with excavated variants

### ISSUE THREAD

**Issue by Sunconure11** [LordDeatHunter/Alloy-Forgery#45]
https://pastebin.com/J9TbqgLr

@lukebemish @LordDeatHunter

**Comment by lukebemish** [comment]
Alright, looks like something messes with the registry in an unexpected fashion. I don't _think_ this is on my side, but if it is feel free to give me another ping or open an issue on EV.

**Comment by Noaaan** [comment]
This issue is not on your side. This is likely an issue where our `DefaultedRegistryMixin` is loading Alloy Forgery way too early, causing an class inheritance error down the lane. We are planning a fix which should mitigate this issue.

**Comment by Noaaan** [comment]
As Sunconure11 mentioned in https://github.com/Safrodev/Archon/issues/4, the issue is related to More Bundles. 
The root of the issue is that they are accidentally sealing the `EnchantmentTarget` class using a Mixin plugin, see https://github.com/BelgianSalamander/MoreBundles/issues/12 for more details on this. 
Once this has been resolved this issue will be closed.

**Comment by Noaaan** [comment]
Closing this as it was fixed in [More Bundles 0.2.1](https://www.curseforge.com/minecraft/mc-mods/more-bundles/files/3755115)
